routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', [HomeController::class, 'index'])->name('home')->middleware('auth');;

Route::name('users.')->prefix('users')->middleware('auth')->group(function (){
    Route::get('/',[UserController::class, 'index'])->name('index')->middleware('permission:user_list');
    Route::post('/',[UserController::class, 'store'])->name('store')->middleware('permission:user_create');
    Route::get('/create',[UserController::class, 'create'])->name('create')->middleware('permission:user_create');
    Route::get('/show/{id}',[UserController::class, 'show'])->name('show')->middleware('permission:user_show');
    Route::get('/edit/{id}',[UserController::class, 'edit'])->name('edit')->middleware('permission:user_edit');
    Route::put('/update/{id}',[UserController::class, 'update'])->name('update')->middleware('permission:user_edit');
    Route::delete('/destroy/{id}',[UserController::class, 'destroy'])->name('destroy')->middleware('permission:user_delete');
});


Route::prefix('roles')->name('roles.')->middleware('auth')->group(function (){
    Route::get('/',[RoleController::class, 'index'])->name('index')->middleware('permission:role_list');
    Route::post('/',[RoleController::class, 'store'])->name('store')->middleware('permission:role_create');
    Route::get('/create',[RoleController::class, 'create'])->name('create')->middleware('permission:role_create');
    Route::get('/show/{id}',[RoleController::class, 'show'])->name('show')->middleware('permission:role_show');
    Route::get('/edit/{id}',[RoleController::class, 'edit'])->name('edit')->middleware('permission:role_edit');
    Route::put('/update/{id}',[RoleController::class, 'update'])->name('update')->middleware('permission:role_edit');
    Route::delete('/destroy/{id}',[RoleController::class, 'destroy'])->name('destroy')->middleware('permission:role_delete');
});

Route::prefix('categories')->name('categories.')->middleware('auth')->group(function (){
    Route::get('/',[CategoryController::class, 'index'])->name('index')->middleware('permission:category_list');
    Route::post('/',[CategoryController::class, 'store'])->name('store')->middleware('permission:category_create');
    Route::get('/create',[CategoryController::class, 'create'])->name('create')->middleware('permission:category_create');
    Route::get('/show/{id}',[CategoryController::class, 'show'])->name('show')->middleware('permission:category_show');
    Route::get('/edit/{id}',[CategoryController::class, 'edit'])->name('edit')->middleware('permission:category_edit');
    Route::put('/update/{id}',[CategoryController::class, 'update'])->name('update')->middleware('permission:category_edit');
    Route::delete('/destroy/{id}',[CategoryController::class, 'destroy'])->name('destroy')->middleware('permission:category_delete');
});

Route::prefix('products')->name('products.')->middleware('auth')->group(function (){
    Route::get('/',[ProductController::class, 'index'])->name('index')->middleware('permission:product_list');
    Route::post('/',[ProductController::class, 'store'])->name('store')->middleware('permission:product_create');
    Route::get('list/',[ProductController::class,'list'])->name('list');
    Route::get('/show/{id}',[ProductController::class, 'show'])->name('show')->middleware('permission:product_show');
    Route::get('/create',[ProductController::class, 'create'])->name('create')->middleware('permission:product_create');
    Route::get('/edit/{id}',[ProductController::class, 'edit'])->name('edit')->middleware('permission:product_edit');
    Route::post('/update/{id}',[ProductController::class, 'update'])->name('update')->middleware('permission:product_edit');
    Route::delete('/destroy/{id}',[ProductController::class, 'destroy'])->name('destroy')->middleware('permission:product_delete');
});

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    use HasFactory;

    protected $table = 'roles';

    protected $fillable = [
        'name',
        'display_name'
    ];

    public function permissions()
    {
        return $this->belongsToMany(Permission::class);
    }

    public function users()
    {
        return $this->belongsToMany(User::class);
    }

    public function hasPermissions($permissionName)
    {
        return $this->permissions->contains('name', $permissionName);
    }

    public function attachPermission($permissionId)
    {
        return $this->permissions()->attach($permissionId);
    }

    public function detachPermission()
    {
        return $this->permissions()->detach();
    }

    public function syncPermission($permissionId)
    {
        return $this->permissions()->sync($permissionId);
    }
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Role\CreateRoleRequest;
use App\Http\Requests\Role\UpdateRoleRequest;
use App\Services\RoleService;
use Illuminate\Http\Request;

class RoleController extends Controller
{
    protected RoleService $roleService;

    public function __construct(RoleService $roleService)
    {
        $this->roleService = $roleService;
    }

    public function index()
    {
        $listRoles = $this->roleService->all();
        return view("admin.roles.index", compact('listRoles'));
    }

    public function show($id)
    {
        $role = $this->roleService->findById($id);
        return view("admin.roles.show", compact('role'));
    }

    public function create()
    {
        return view("admin.roles.create");
    }

    public function store(CreateRoleRequest $request)
    {
        $this->roleService->store($request);
        return redirect()->route('roles.index')->with('message', "Create role success.");
    }

    public function edit($id)
    {
        $role = $this->roleService->findById($id);
        return view("admin.roles.edit", compact('role'));
    }

    public function update(UpdateRoleRequest $request, $id)
    {
        $this->roleService->update($request, $id);
        return redirect()->route("roles.index")->with("message", "Update role success!");
    }

    public function destroy($id)
    {
        $this->roleService->destroy($id);
        return redirect()->back()->with("message", "Delete role success.");
    }
}

resources/views/admin/roles/create.blade.php
@extends('admin.layouts.layouts')
@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <h4 class="page-title">Create Role</h4>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('roles.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="modal-body">
                            @include('admin.layouts.form-errors')
                            <div class="mb-3">
                                <label>Name</label>
                                <input type="text" name="name" value="{{ old("name") }}" class="form-control" placeholder="Name">
                            </div>
                            <div class="mb-3">
                                <label>Display name</label>
                                <input type="text" name="display_name" value="{{ old("display_name") }}" class="form-control" placeholder="Display name">
                            </div>
                            <div class="mb-3 row">
                                <label>Permission</label>
                                <div class="checkbox select-all col-sm-1">
                                    <input id="all" type="checkbox" />
                                    <label for="all">Select all</label>
                                </div>
                                @foreach($group_permission as $group => $values)
                                    <div class="col-sm-2">
                                        {{ $group }}
                                        @foreach($values as $value)
                                            <div class="checkbox rows">
                                                <input id="box-{{ $value->id }}" class="select-item" name="permission_id[]" value="{{ $value->id }}" type="checkbox"
                                                    {{ (is_array(old("permission_id")) and in_array($value->id, old("permission_id"))) ? 'checked' : '' }}/>
                                                <label for="box-{{ $value->id }}">{{ $value->display_name }}</label>
                                            </div>
                                        @endforeach
                                    </div>
                                @endforeach
                            </div>
                        </div>
                        <div class="modal-footer">
                            <a type="button" href="{{ url()->previous() }}" class="btn btn-secondary btn-button">Back</a>
                            @hasPermission('role_create')
                            <button type="submit" class="btn btn-primary btn-button">Create</button>
                            @endhasPermission
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/roles/edit.blade.php
@extends('admin.layouts.layouts')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="page-title-box">
                    <h4 class="page-title">Update Role</h4>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <form action="{{ route('roles.update',$role->id) }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @method('put')
                            <div class="modal-body">
                                @include('admin.layouts.form-errors')
                                <div class="mb-3">
                                    <label>Name</label>
                                    <input type="text" name="name" class="form-control" value="{{ $role->name }}" placeholder="Name">
                                </div>
                                <div class="mb-3">
                                    <label>Display Name</label>
                                    <input type="text" name="display_name" class="form-control" value="{{ $role->display_name }}" placeholder="Display name">
                                </div>
                                @if($role->name != "super-admin")
                                    <div class="mb-3 row">
                                        <label>Permission</label>
                                        <div class="checkbox select-all col-sm-1">
                                            <input id="all" type="checkbox" />
                                            <label for="all">Select all</label>
                                        </div>
                                        @foreach($group_permission as $group => $values)
                                            <div class="col-sm-2">
                                                {{ $group }}
                                                @foreach($values as $value)
                                                    <div class="checkbox rows">
                                                        <input id="box-{{ $value->id }}" class="select-item" name="permission_id[]" value="{{ $value->id }}" type="checkbox"
                                                            {{$role->permissions->contains('id',$value->id) ? 'checked' : ''}}/>
                                                        <label for="box-{{ $value->id }}">{{ $value->display_name }}</label>
                                                    </div>
                                                @endforeach
                                            </div>
                                        @endforeach
                                    </div>
                                @endif
                            </div>
                            <div class="modal-footer">
                                <a type="button" href="{{ url()->previous() }}" class="btn btn-secondary btn-button">Back</a>
                                <button type="submit" class="btn btn-primary btn-button">Update</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/roles/index.blade.php
@extends("admin.layouts.layouts")
@section("content")
    <div class="container-fluid">

        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box">
                    <h4 class="page-title">Role</h4>
                </div>
            </div>
        </div>
        <!-- end page title -->

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row mb-2">
                            <div class="col-sm-4">
                                @hasPermission('role_create')
                                <a href="{{ route("roles.create") }}">
                                    <button type="button" class="btn btn-danger mb-2">
                                        <i class="mdi mdi-plus-circle me-2"></i>Add Role
                                    </button>
                                </a>
                                @endhasPermission
                            </div>
                            <!-- Modal -->
                        </div>
                        <div class="table-responsive">
                            <table class="table table-centered table-bordered w-100 dt-responsive nowrap">
                                <thead class="table-light">
                                <tr style="white-space: nowrap;">
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Display Name</th>
                                    <th>Permission</th>
                                    <th style="width: 85px;text-align: center">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @if(count($listRoles) != 0)
                                @foreach($listRoles as $item)
                                    <tr>
                                        <td>{{ $item->id }}</td>
                                        <td>{{ $item->name }}</td>
                                        <td>{{ $item->display_name }}</td>
                                        <td>
                                            @if($item->name == "super-admin")
                                                <span class="badge bg-success">All</span>
                                            @else
                                                @foreach($item->permissions as $permission)
                                                    <span class="badge bg-success">{{ $permission->display_name }}</span>
                                                @endforeach
                                            @endif
                                        </td>
                                        <td>
                                           <div class="container">
                                               <div class="flex-class justify-content-center">
                                                   <div class="col-sm-4">
                                                       <a href="{{ route('roles.show', $item->id) }}"> <button type="button" class="btn btn-primary"><i class="dripicons-information"></i></button></a>
                                                   </div>
                                                   @if($item->name != "super-admin")
                                                   @hasPermission('role_edit')
                                                   <div class="col-sm-4">
                                                       <a href="{{ route('roles.edit', $item->id) }}"> <button type="button" class="btn btn-secondary">  <i class="dripicons-document-edit"></i></button></a>
                                                   </div>
                                                   @endhasPermission
                                                   @hasPermission('role_delete')
                                                       <div class="col-sm-4">
                                                           <form id="delete-{{$item->name}}-{{$item->id}}" action="{{ route('roles.destroy',$item->id) }}" method="POST">
                                                               @csrf
                                                               @method('DELETE')
                                                           </form>
                                                           <button data-id="{{$item->id}}"
                                                                   data-name="{{ $item->name }}"
                                                                   data-name-show="{{ $item->display_name }}"
                                                                   type="submit" class="btn btn-danger btn-delete">
                                                               <i class="dripicons-trash"></i>
                                                           </button>
                                                       </div>
                                                   @endif
                                                   @endhasPermission
                                               </div>
                                           </div>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                                @else
                                    <tbody>
                                    <tr>
                                        <td colspan="5" class="text-center"><span style="font-size: 25px; color: #d8d8d8">No data...</span></td>
                                    </tr>
                                    </tbody>
                                @endif
                            </table>
                            {{ $listRoles->appends(request()->all())->links() }}
                        </div>
                    </div> <!-- end card-body-->
                </div> <!-- end card-->
            </div> <!-- end col -->
        </div>
    </div>
    @push('scripts')
        <script src="{{asset('js/role.js')}}"></script>
    @endpush
@endsection

resources/views/admin/roles/show.blade.php
@extends("admin.layouts.layouts")
@section("content")
    <div class="container-fluid">
        <!-- start page title -->
        <div class="row">
            <div class="col-md-4" style="margin: auto;padding: 10px;text-align: center">
                <h2 class="page-title">Detail role {{ $role->name }}</h2>

            </div>
        </div>
        <!-- end page title -->
        <div class="row">
            <div class="col-md-6" style="margin: auto">
                <div class="card">
                    <div class="card-body">
                        <dl class="row">
                            <dt class="col-sm-4">Id :</dt>
                            <dd class="col-sm-8">{{ $role->id }}</dd>
                            <dt class="col-sm-4">Name :</dt>
                            <dd class="col-sm-8">{{ $role->name }}</dd>
                            <dt class="col-sm-4">Display name :</dt>
                            <dd class="col-sm-8">{{ $role->display_name }}</dd>
                            @if($role->name != "super-admin")
                                <dt class="col-sm-4">Permission :</dt>
                                <dd class="col-sm-8">
                                    <div class="row">
                                        @foreach($role->permissions as $item)
                                            <div class="col-sm-4">
                                                <span class="badge bg-success">{{ $item->display_name }}</span>
                                            </div>
                                        @endforeach
                                    </div>
                                </dd>
                            @endif
                        </dl>
                    </div>
                    <a type="button" href="{{ url()->previous() }}" class="btn btn-primary btn-button">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection