routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', [HomeController::class, 'index'])->name('home')->middleware('auth');;

Route::name('users.')->prefix('users')->middleware('auth')->group(function (){
    Route::get('/',[UserController::class, 'index'])->name('index')->middleware('permission:user_list');
    Route::post('/',[UserController::class, 'store'])->name('store')->middleware('permission:user_create');
    Route::get('/create',[UserController::class, 'create'])->name('create')->middleware('permission:user_create');
    Route::get('/show/{id}',[UserController::class, 'show'])->name('show')->middleware('permission:user_show');
    Route::get('/edit/{id}',[UserController::class, 'edit'])->name('edit')->middleware('permission:user_edit');
    Route::put('/update/{id}',[UserController::class, 'update'])->name('update')->middleware('permission:user_edit');
    Route::delete('/destroy/{id}',[UserController::class, 'destroy'])->name('destroy')->middleware('permission:user_delete');
});


Route::prefix('roles')->name('roles.')->middleware('auth')->group(function (){
    Route::get('/',[RoleController::class, 'index'])->name('index')->middleware('permission:role_list');
    Route::post('/',[RoleController::class, 'store'])->name('store')->middleware('permission:role_create');
    Route::get('/create',[RoleController::class, 'create'])->name('create')->middleware('permission:role_create');
    Route::get('/show/{id}',[RoleController::class, 'show'])->name('show')->middleware('permission:role_show');
    Route::get('/edit/{id}',[RoleController::class, 'edit'])->name('edit')->middleware('permission:role_edit');
    Route::put('/update/{id}',[RoleController::class, 'update'])->name('update')->middleware('permission:role_edit');
    Route::delete('/destroy/{id}',[RoleController::class, 'destroy'])->name('destroy')->middleware('permission:role_delete');
});

Route::prefix('categories')->name('categories.')->middleware('auth')->group(function (){
    Route::get('/',[CategoryController::class, 'index'])->name('index')->middleware('permission:category_list');
    Route::post('/',[CategoryController::class, 'store'])->name('store')->middleware('permission:category_create');
    Route::get('/create',[CategoryController::class, 'create'])->name('create')->middleware('permission:category_create');
    Route::get('/show/{id}',[CategoryController::class, 'show'])->name('show')->middleware('permission:category_show');
    Route::get('/edit/{id}',[CategoryController::class, 'edit'])->name('edit')->middleware('permission:category_edit');
    Route::put('/update/{id}',[CategoryController::class, 'update'])->name('update')->middleware('permission:category_edit');
    Route::delete('/destroy/{id}',[CategoryController::class, 'destroy'])->name('destroy')->middleware('permission:category_delete');
});

Route::prefix('products')->name('products.')->middleware('auth')->group(function (){
    Route::get('/',[ProductController::class, 'index'])->name('index')->middleware('permission:product_list');
    Route::post('/',[ProductController::class, 'store'])->name('store')->middleware('permission:product_create');
    Route::get('list/',[ProductController::class,'list'])->name('list');
    Route::get('/show/{id}',[ProductController::class, 'show'])->name('show')->middleware('permission:product_show');
    Route::get('/create',[ProductController::class, 'create'])->name('create')->middleware('permission:product_create');
    Route::get('/edit/{id}',[ProductController::class, 'edit'])->name('edit')->middleware('permission:product_edit');
    Route::post('/update/{id}',[ProductController::class, 'update'])->name('update')->middleware('permission:product_edit');
    Route::delete('/destroy/{id}',[ProductController::class, 'destroy'])->name('destroy')->middleware('permission:product_delete');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'phone',
//        'address',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function roles()
    {
        return $this->belongsToMany(Role::class);
    }

    public function hasRoles($rolesName)
    {
        return $this->roles->contains('name', $rolesName);
    }

    public function hasPermission($permissionName)
    {
        $roles = $this->roles;
        foreach ($roles as $role) {
            if ($role->hasPermissions($permissionName)) {
                return true;
            }
        }
        return false;
    }

    public function isSupperAdmin()
    {
        return $this->hasRoles('super-admin');
    }

    public function attachRole($roleId)
    {
        return $this->roles()->attach($roleId);
    }

    public function syncRole($roleId)
    {
        return $this->roles()->sync($roleId);
    }

    public function detachRole()
    {
        return $this->roles()->detach();
    }

    public function scopeSearchWithName($query, $name)
    {
        return $name ? $query->where('name', 'like', '%' . $name . '%') : null;
    }

    public function scopeSearchWithEmail($query, $email)
    {
        return $email ? $query->where('email', $email) : null;
    }

    public function scopeSearchWithRoleId($query, $roleId)
    {
        return $roleId ? $query->whereHas('roles', fn($q) => $q->where('role_id', $roleId)) : null;
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\User\CreateUserRequest;
use App\Http\Requests\User\UpdateUserRequest;
use App\Services\UserService;
use Illuminate\Http\Request;

class UserController extends Controller
{
    protected UserService $userService;

    public function __construct(UserService $userService)
    {
        $this->userService = $userService;
    }

    public function index(Request $request)
    {
        $users = $this->userService->search($request);
        return view("admin.users.index", compact('users'));
    }

    public function show($id)
    {
        $user = $this->userService->findById($id);
        return view("admin.users.show", compact('user'));
    }

    public function create()
    {
        return view("admin.users.create");
    }

    public function store(CreateUserRequest $request)
    {
        $this->userService->store($request);
        return redirect()->route('users.index')->with("message", "Create user success.");
    }

    public function edit($id)
    {
        $user = $this->userService->findById($id);
        return view("admin.users.edit", compact('user'));
    }

    public function update(UpdateUserRequest $request, $id)
    {
        $this->userService->update($request, $id);
        return redirect()->route("users.index")->with("message", "Update user success.");
    }

    public function destroy($id)
    {
        $this->userService->destroy($id);
        return redirect()->back()->with('message', "Delete user success.");
    }
}

resources/views/admin/users/create.blade.php
@extends('admin.layouts.layouts')
@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <h4 class="page-title">Create User</h4>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('users.store') }}" data-action="{{ route('users.store') }}" id="form-add" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="modal-body">
                            @include('admin.layouts.form-errors')
                            <div class="mb-3">
                                <label>Name</label>
                                <input type="text" name="name" value="{{ old("name") }}" class="form-control" placeholder="Name">
                            </div>
                            <div class="mb-3">
                                <label>Email address</label>
                                <input type="email" name="email" value="{{ old("email") }}" class="form-control" placeholder="Email">
                            </div>
                            <div class="mb-3">
                                <label>Address</label>
                                <input type="text" name="address" value="{{ old("address") }}" class="form-control" placeholder="Address">
                            </div>

                            <div class="mb-3">
                                <label>Phone</label>
                                <input type="number" name="phone" value="{{ old("phone") }}" class="form-control" placeholder="Phone">
                            </div>
                            <div class="mb-3">
                                <label for="password" class="form-label"> Password</label>
                                <div class="input-group input-group-merge">
                                    <input type="password" id="password" value="{{ old("password") }}" name="password" class="form-control" placeholder="Enter your password">
                                    <div class="input-group-text" data-password="false">
                                        <span class="password-eye"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="mb-3">
                                @if($roles->first() == null || auth()->user()->isSupperAdmin())
                                    <label>Role</label>
                                    <div class="checkbox select-all">
                                        <input id="all" type="checkbox" />
                                        <label for="all">Select all</label>
                                    </div>
                                    @foreach($roles as $role)
                                        <div class="checkbox rows col-md-4">
                                            <input id="box-{{ $role->id }}" class="select-item" name="role_id[]" value="{{ $role->id }}"
                                                   type="checkbox" {{ (is_array(old("role_id")) and in_array($role->id, old("role_id"))) ? 'checked' : '' }}/>
                                            <label for="box-{{ $role->id }}">{{ $role->display_name }}</label>
                                        </div>
                                    @endforeach
                                @endif
                            </div>
                        </div>
                        <div class="modal-footer">
                            <a type="button" href="{{ route("users.index") }}" class="btn btn-secondary btn-button">Back</a>
                            <button type="submit" class="btn btn-primary btn-button">Create</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/users/edit.blade.php
@extends('admin.layouts.layouts')
@section('content')
<div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="page-title-box">
                    <h4 class="page-title">Update User</h4>
                </div>
            </div>
        </div>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('users.update',$user->id) }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('put')
                        @include('admin.layouts.form-errors')
                        <div class="modal-body">
                            <div class="mb-3">
                                <label>Name</label>
                                <input type="text" name="name" class="form-control" value="{{ $user->name }}" placeholder="Name">
                            </div>
                            <div class="mb-3">
                                <label>Email address</label>
                                <input type="email" name="email" class="form-control" value="{{ $user->email }}" placeholder="Email">
                            </div>

                            <div class="mb-3">
                                <label>Address</label>
                                <input type="text" name="address" class="form-control" value="{{ $user->address }}" placeholder="Address">
                            </div>

                            <div class="mb-3">
                                <label>Phone</label>
                                <input type="number" name="phone" class="form-control" value="{{ $user->phone }}" placeholder="Phone">
                                @error('phone')
                                    <span class="alert alert-danger">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="mb-3">
                                <label for="password" class="form-label">Password</label>
                                <div class="input-group input-group-merge">
                                    <input type="password" id="password" name="password" class="form-control" placeholder="Enter your password">
                                    @error('password')
                                        <div class="alert alert-danger">
                                            <strong>{{ $message }}</strong>
                                        </div>
                                    @enderror
                                    <div class="input-group-text" data-password="false">
                                        <span class="password-eye"></span>
                                    </div>
                                </div>
                            </div>
                            @if(!$user->isSupperAdmin())
                            <div class="mb-3">
                                <label>Role</label>
                                <div class="checkbox select-all">
                                    <input id="all" type="checkbox" />
                                    <label for="all">Select all</label>
                                </div>
                                @foreach($roles as $role)
                                    <div class="checkbox rows col-md-4">
                                        <input id="box-{{ $role->id }}" class="select-item" name="role_id[]" {{ $user->roles->contains('id',$role->id ) ? 'checked' : '' }} value="{{ $role->id }}" type="checkbox" />
                                        <label for="box-{{ $role->id }}">{{ $role->display_name }}</label>
                                    </div>
                                @endforeach
                            </div>
                            @endif
                        </div>
                        <div class="modal-footer">
                            <a type="button" href="{{ url()->previous() }}" class="btn btn-secondary btn-button">Back</a>
                            <button type="submit" class="btn btn-primary btn-button">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/users/index.blade.php
@extends("admin.layouts.layouts")
@section("content")
    <div class="container-fluid">

        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box">
                    <h4 class="page-title">User</h4>
                </div>
            </div>
        </div>
        <!-- end page title -->

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row mb-2">
                            <div class="col-md-2">
                                @hasPermission('user_create')
                                <a href="{{ route("users.create") }}">
                                    <button type="button" class="btn btn-danger mb-2" data-bs-toggle="modal" data-bs-target="#exampleModal">
                                        <i class="mdi mdi-plus-circle me-2"></i>Add User
                                    </button>
                                </a>
                                @endhasPermission
                            </div>
                            <div class=" col-md-10 set-search">
                                <form action="" method="get">
                                    <input name="name" class="form-control" value="{{ request()->name ?? '' }}" style="width: 20%" placeholder="Enter name...">
                                    <input name="email" class="form-control" style="width: 20%" value="{{ request()->email ?? '' }}" placeholder="Enter Email...">
                                    <select name="role_id" class="form-control" style="width: 10%; margin-right: 5px;margin-left: 5px">
                                        <option value="">None</option>
                                        @foreach($roles as $role)
                                            <option {{ $role->id == request('role_id') ? 'selected' : '' }} value="{{ $role->id }}">
                                                {{ $role->display_name }}
                                            </option>
                                        @endforeach
                                    </select>
                                    <button type="reset" class="btn btn-secondary">Reset</button>
                                    <button type="submit" class="btn btn-primary" style="margin-left: 5px">Search</button>
                                </form>
                            </div>
                        </div>
                        <div class="table-responsive">

                            <table class="table table-centered table-bordered w-100 dt-responsive nowrap">
                                <thead class="table-light">
                                <tr>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Phone</th>
                                    <th style="width: 85px;text-align: center">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @if(count($users) != 0)
                                @foreach($users as $item)
                                    <tr>
                                        <td>{{ $item->id }}</td>
                                        <td>{{ $item->name }}</td>
                                        <td>{{ $item->email }}</td>
                                        <td>{{ $item->phone }}</td>
                                        <td>
                                            <div class="container">
                                                <div class="flex-class justify-content-center">
                                                    <div class="col-sm-4">
                                                        <a href="{{ route('users.show', $item->id) }}"> <button type="button" class="btn btn-primary">
                                                                <i class="dripicons-information"></i>
                                                            </button>
                                                        </a>
                                                    </div>
                                                    @if($item->hasRoles('super-admin') == false)
                                                    @hasPermission('user_edit')
                                                        <div class="col-sm-4" >
                                                            <a href="{{ route('users.edit', $item->id) }}">
                                                                <button type="button" class="btn btn-secondary">
                                                                    <i class="dripicons-document-edit"></i>
                                                                </button>
                                                            </a>
                                                        </div>
                                                        @endhasPermission
                                                        @hasPermission('user_delete')
                                                            @if(auth()->user()->id != $item->id && $item->email != "admin@gmail.com")
                                                            <div class="col-sm-4">
                                                                <form id="delete-{{$item->phone}}-{{$item->id}}" action="{{ route('users.destroy',$item->id) }}" method="POST">
                                                                    @csrf
                                                                    @method('DELETE')
                                                                </form>
                                                                <button data-id="{{$item->id}}"
                                                                        data-name="{{ $item->phone }}"
                                                                        data-name-show="{{ $item->name }}"
                                                                        type="submit" class="btn btn-danger btn-delete">
                                                                    <i class="dripicons-trash"></i>
                                                                </button>
                                                            </div>
                                                            @endif
                                                        @endhasPermission
                                                    @endif
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                                @else
                                    <tbody>
                                    <tr>
                                        <td colspan="5" class="text-center"><span style="font-size: 25px; color: #d8d8d8">No data...</span></td>
                                    </tr>
                                    </tbody>
                                @endif
                            </table>
                            {{ $users->appends(request()->all())->links('vendor.pagination.bootstrap-5') }}
                        </div>
                    </div> <!-- end card-body-->
                </div> <!-- end card-->
            </div> <!-- end col -->
        </div>
    </div>
    @push('scripts')
        <script src="{{asset('js/user.js')}}"></script>
    @endpush
@endsection

resources/views/admin/users/show.blade.php
@extends("admin.layouts.layouts")
@section("content")
    <div class="container-fluid">
        <!-- start page title -->
        <div class="row">
            <div class="col-md-4" style="margin: auto;padding: 10px;text-align: center">
                <h2 class="page-title">Detail user {{ $user->name }}</h2>

            </div>
        </div>
        <!-- end page title -->
        <div class="row">
            <div class="col-md-6" style="margin: auto">
                <div class="card">
                    <div class="card-body">
                        <dl class="row">
                            <dt class="col-sm-4">Id :</dt>
                            <dd class="col-sm-8">{{ $user->id }}</dd>
                            <dt class="col-sm-4">Name :</dt>
                            <dd class="col-sm-8">{{ $user->name }}</dd>
                            <dt class="col-sm-4">Email address :</dt>
                            <dd class="col-sm-8">{{ $user->email }}</dd>
                            <dt class="col-sm-4">Phone :</dt>
                            <dd class="col-sm-8">{{ $user->phone }}</dd>
                            <dt class="col-sm-4">Role :</dt>
                            <dd class="col-sm-8">
                                @if($user->hasRoles('super-admin'))
                                    <div class="col-sm-2">
                                        <span class="badge bg-success">Super Admin</span>
                                    </div>
                                @else
                                    @foreach($user->roles as $item)
                                        <div class="col-sm-2">
                                            <span class="badge bg-success">{{ $item->display_name }}</span>
                                        </div>
                                    @endforeach
                                @endif
                            </dd>
                        </dl>
                    </div>
                    <a type="button" href="{{ url()->previous() }}" class="btn btn-primary btn-button">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection