routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', [HomeController::class, 'index'])->name('home')->middleware('auth');;

Route::name('users.')->prefix('users')->middleware('auth')->group(function (){
    Route::get('/',[UserController::class, 'index'])->name('index')->middleware('permission:user_list');
    Route::post('/',[UserController::class, 'store'])->name('store')->middleware('permission:user_create');
    Route::get('/create',[UserController::class, 'create'])->name('create')->middleware('permission:user_create');
    Route::get('/show/{id}',[UserController::class, 'show'])->name('show')->middleware('permission:user_show');
    Route::get('/edit/{id}',[UserController::class, 'edit'])->name('edit')->middleware('permission:user_edit');
    Route::put('/update/{id}',[UserController::class, 'update'])->name('update')->middleware('permission:user_edit');
    Route::delete('/destroy/{id}',[UserController::class, 'destroy'])->name('destroy')->middleware('permission:user_delete');
});


Route::prefix('roles')->name('roles.')->middleware('auth')->group(function (){
    Route::get('/',[RoleController::class, 'index'])->name('index')->middleware('permission:role_list');
    Route::post('/',[RoleController::class, 'store'])->name('store')->middleware('permission:role_create');
    Route::get('/create',[RoleController::class, 'create'])->name('create')->middleware('permission:role_create');
    Route::get('/show/{id}',[RoleController::class, 'show'])->name('show')->middleware('permission:role_show');
    Route::get('/edit/{id}',[RoleController::class, 'edit'])->name('edit')->middleware('permission:role_edit');
    Route::put('/update/{id}',[RoleController::class, 'update'])->name('update')->middleware('permission:role_edit');
    Route::delete('/destroy/{id}',[RoleController::class, 'destroy'])->name('destroy')->middleware('permission:role_delete');
});

Route::prefix('categories')->name('categories.')->middleware('auth')->group(function (){
    Route::get('/',[CategoryController::class, 'index'])->name('index')->middleware('permission:category_list');
    Route::post('/',[CategoryController::class, 'store'])->name('store')->middleware('permission:category_create');
    Route::get('/create',[CategoryController::class, 'create'])->name('create')->middleware('permission:category_create');
    Route::get('/show/{id}',[CategoryController::class, 'show'])->name('show')->middleware('permission:category_show');
    Route::get('/edit/{id}',[CategoryController::class, 'edit'])->name('edit')->middleware('permission:category_edit');
    Route::put('/update/{id}',[CategoryController::class, 'update'])->name('update')->middleware('permission:category_edit');
    Route::delete('/destroy/{id}',[CategoryController::class, 'destroy'])->name('destroy')->middleware('permission:category_delete');
});

Route::prefix('products')->name('products.')->middleware('auth')->group(function (){
    Route::get('/',[ProductController::class, 'index'])->name('index')->middleware('permission:product_list');
    Route::post('/',[ProductController::class, 'store'])->name('store')->middleware('permission:product_create');
    Route::get('list/',[ProductController::class,'list'])->name('list');
    Route::get('/show/{id}',[ProductController::class, 'show'])->name('show')->middleware('permission:product_show');
    Route::get('/create',[ProductController::class, 'create'])->name('create')->middleware('permission:product_create');
    Route::get('/edit/{id}',[ProductController::class, 'edit'])->name('edit')->middleware('permission:product_edit');
    Route::post('/update/{id}',[ProductController::class, 'update'])->name('update')->middleware('permission:product_edit');
    Route::delete('/destroy/{id}',[ProductController::class, 'destroy'])->name('destroy')->middleware('permission:product_delete');
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $table = 'products';

    protected $fillable = [
        'name',
        'price',
        'quantity',
        'description',
        'image',
    ];

    public $timestamps = false;

    public function categories()
    {
        return $this->belongsToMany(Category::class);
    }
    public function attachCategory($categoryId)
    {
        return $this->categories()->attach($categoryId);
    }

    public function syncCategory($categoryId)
    {
        return $this->categories()->sync($categoryId);
    }

    public function scopeWithName($query, $name)
    {
        return $name ? $query->where('name', 'like', '%' . $name . '%') : null;
    }

    public function scopeWithMinPrice($query, $minPrice)
    {
        return $minPrice ? $query->where('price', '>=', $minPrice) : null;
    }

    public function scopeWithMaxPrice($query, $maxPrice)
    {
        return $maxPrice ? $query->where('price', '<=', $maxPrice) : null;
    }

    public function scopeWithCategoryName($query, $categoryId)
    {
//        return $categoryId ? $query->whereHas('categories', function ($q) use ($categoryId) {
//            $q->where('category_id', $categoryId);
//        }) : null;
        return $categoryId ? $query->whereHas('categories', fn($q) => $q->where('category_id', $categoryId)) : null;
    }

    public function getImageAttribute($image)
    {
        return $image ? asset("upload/images/products/". $image) : asset("upload/images/default.jpg");
    }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Product\UpdateProductRequest;
use App\Http\Requests\Product\CreateProductRequest;
use App\Http\Resources\Product\ProductResource;
use App\Services\ProductService;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class ProductController extends Controller
{
    protected ProductService $productService;

    public function __construct(ProductService $productService)
    {
        $this->productService = $productService;
    }

    public function index()
    {
        return view("admin.products.index");
    }

    public function list(Request $request)
    {
        $products = $this->productService->search($request);
        return view("admin.products.list", compact('products'))->render();
    }

    public function show($id)
    {
        $product = $this->productService->findById($id);
        return view("admin.products.show", compact('product'));
    }

    public function create()
    {
        return view("admin.products.create");
    }

    public function store(CreateProductRequest $request)
    {
        $product = $this->productService->store($request);
        $productResource = new ProductResource($product);
        return $this->sentSuccessResponse($productResource, 'Create product success.', Response::HTTP_CREATED);
    }

    public function edit($id)
    {
        $product = $this->productService->findById($id);
        return view("admin.products.edit", compact('product'));
    }

    public function update(UpdateProductRequest $request, $id)
    {
        $product = $this->productService->update($request, $id);
        return $this->sentSuccessResponse($product, 'Update product success.', Response::HTTP_OK);
    }

    public function destroy($id)
    {
        $this->productService->destroy($id);
        return $this->sentSuccessResponse('', 'Delete product success.', Response::HTTP_OK);
    }
}

resources/views/admin/products/create.blade.php
<div id="modal-form-create" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog ">
        <div class="modal-content">
            <div class="modal-body">
                <div class="text-center mt-2 mb-4">
                    <h2 class="page-title text-danger">Create Product</h2>
                    <hr>
                </div>
                <form data-action="{{ route('products.store') }}" id="addProductForm" method="POST" class="ps-3 pe-3" enctype="multipart/form-data">
                    @csrf
                    <div class="mb-3">
                        <label>Name</label>
                        <input type="text" name="name" id="name" class="form-control" placeholder="Name">
                        <div class="text-danger error error-name"></div>
                    </div>
                    <div class="mb-3">
                        <label>Price</label>
                        <input type="number" name="price" id="price" class="form-control" placeholder="Price">
                        <div class="text-danger error error-price"></div>
                    </div>
                    <div class="mb-3">
                        <label>Description</label>
                        <input type="text" name="description" id="description" class="form-control" placeholder="Description">
                        <div class="text-danger error error-description"></div>
                    </div>
                    <div class="mb-3">
                        <label>Quantity</label>
                        <input type="number" name="quantity" id="quantity" class="form-control" value="1" placeholder="Quantity">
                        <div class="text-danger error error-quantity"></div>
                    </div>
                    <div class="mb-3">
                        <label for="password" class="form-label">Image</label>
                        <input type="file" name="image" class="form-control image" id="image">
                        <div class="show-image" style="width: 25%;">

                        </div>
                        <div class="text-danger error error-image"></div>
                    </div>
                    <div class="mb-3 row">
                        <label>Category</label>
                        <select class="selectpicker" name="category_ids[]" multiple data-live-search="true">
                            @foreach($categories as $category)
                                <option value="{{$category->id}}">{{$category->name}}</option>
                            @endforeach
                        </select>
                        <div class="text-danger error error-category_ids"></div>
                    </div>
                    <hr>
                    <div class="mb-3 text-center">
                        <button class="btn btn-rounded btn-secondary" type="button" data-bs-dismiss="modal">Close</button>
                        <button class="btn btn-rounded btn-primary" type="submit" id="btn-create">Create</button>
                    </div>
                </form>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

resources/views/admin/products/edit.blade.php
<form data-action="{{ route('products.update',$product->id) }}" id="updateProductForm" method="post" enctype="multipart/form-data">
    @csrf
    <div class="mb-3">
        <label>Name</label>
        <input type="text" name="name" class="form-control" value="{{ $product->name }}">
        <div class="text-danger error error-name"></div>
    </div>
    <div class="mb-3">
        <label>Price</label>
        <input type="number" name="price" class="form-control" value="{{ $product->price }}">
        <div class="text-danger error error-price"></div>
    </div>
    <div class="mb-3">
        <label class="form-label">Image</label>
        <input type="file" value="" class="form-control image" name="image">
        <div class="show-image" style="width: 25%">
            <img src="{{ $product->image }}" width="100%">
        </div>
        <div class="text-danger error error-image"></div>
    </div>
    <div class="mb-3">
        <label>Quantity</label>
        <input type="number" name="quantity" class="form-control" value="{{ $product->quantity }}">
        <div class="text-danger error error-quantity"></div>
    </div>
    <div class="mb-3">
        <label>Description</label>
        <input type="text" name="description" class="form-control" value="{{ $product->description }}">
        <div class="text-danger error error-description"></div>
    </div>
    <div class="mb-3 set-height-cate">
        <label>Category</label>
        <select class="selectpicker" name="category_ids[]" multiple>
            @foreach($categories as $category)
                <option {{$product->categories->contains('id',$category->id) ? 'selected' : ''}} value="{{$category->id}}">{{$category->name}}</option>
            @endforeach
        </select>
        <div class="text-danger error error-category_ids"></div>
    </div>
    <hr>
    <div class="mb-3 text-center">
        <button class="btn btn-rounded btn-secondary" type="button" data-bs-dismiss="modal">Close</button>
        <button class="btn btn-rounded btn-primary" type="submit" id="btn-update">Update</button>
    </div>
</form>

<script>
    $(".selectpicker").selectpicker('refresh');
</script>

resources/views/admin/products/index.blade.php
@extends("admin.layouts.layouts")
@section("content")
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="page-title-box">
                    <h4 class="page-title">Product</h4>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row mb-2">
                            <div class="col-md-2">
                                @hasPermission('product_create')
                                <button type="button" class="btn btn-danger mb-2" id="btn-add-new-product"
                                        data-bs-toggle="modal" data-bs-target="#modal-form-create">
                                    <i class="mdi mdi-plus-circle me-2"></i>
                                    Add Product
                                </button>
                                @endhasPermission
                            </div>
                            <div class=" col-md-10 set-search">
                                <form id="myForm" method="get">
                                    <input name="name" class="form-control product_name" value="{{ request()->name ?? '' }}"
                                           style="width: 20%" placeholder="Enter name...">
                                    <select id="category_id" name="category_ids" class="form-control"
                                            style="width: 10%; margin-right: 5px;margin-left: 5px">
                                        <option value=""><span style="color: #ada8a8">Category</span></option>
                                        @foreach($categories as $category)
                                            <option
                                                {{ $category->id == request('category_ids') ? 'selected' : '' }} value="{{ $category->id }}">
                                                {{ $category->name }}
                                            </option>
                                        @endforeach
                                    </select>
                                    <input name="min_price" type="number" class="form-control min_price" style="width: 12%"
                                           value="{{ request()->min_price ?? '' }}" placeholder="Enter min price..">
                                    <input name="max_price" type="number" class="form-control max_price" style="width: 12%"
                                           value="{{ request()->max_price ?? '' }}" placeholder="Enter max price..">
{{--                                    <button type="submit" class="btn btn-primary" style="margin-left: 5px">Search--}}
{{--                                    </button>--}}
                                </form>
                            </div>
                        </div>
                        <div id="list" data-action="{{ route('products.list') }}">

                        </div>
                    </div> <!-- end card-body-->
                </div> <!-- end card-->
            </div> <!-- end col -->
        </div>
    </div>

    @include('admin.products.create')
    @hasPermission('product_edit')
    <div id="modal-form-update" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body set-modal">
                    <div class="text-center mt-2 mb-4">
                        <h2 class="page-title text-danger">Edit Product</h2>
                        <hr>
                    </div>
                    <div id="edit">

                    </div>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    @endhasPermission

    @hasPermission('product_show')
    <div id="modal-form-show" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body set-modal">
                    <div class="text-center mt-2 mb-4">
                        <h2 class="page-title text-danger">Detail Product</h2>
                        <hr>
                    </div>
                    <div id="show">

                    </div>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    @endhasPermission
@endsection
@push('scripts')
    <script src="{{ asset("js/product.js") }}"></script>
@endpush

resources/views/admin/products/list.blade.php
<div class="table-responsive">
    <table class="table table-centered table-bordered w-100 dt-responsive nowrap">
        <thead class="table-light">
        <tr>
            <th>ID</th>
            <th>Image</th>
            <th>Name</th>
            <th>Price</th>
            <th style="width: 85px;text-align: center">Action</th>
        </tr>
        </thead>
        @if(count($products) != 0)
            <tbody>
            @foreach($products as $item)
                <tr>
                    <td class="text-center">{{ $item->id }}</td>
                    <td style="width: 10%"><img src="{{ $item->image }}" style="width: 100%;height: 100px" alt=""></td>
                    <td>{{ $item->name }}</td>
                    <td>{{ number_format($item->price) }} VND</td>
                    <td>
                        <div class="container">
                            <div class="flex-class justify-content-center">
                                @hasPermission('product_show')
                                <div class="col-sm-4">
                                    <button type="button" class="btn btn-primary btn-show-product"
                                            data-action="{{ route('products.show', $item->id) }}"
                                            data-bs-target="#modal-form-show"
                                            data-bs-toggle="modal">
                                        <i class="dripicons-information"></i>
                                    </button>
                                </div>
                                @endhasPermission
                                @hasPermission('product_edit')
                                <div class="col-sm-4">
                                    <button type="button" class="btn btn-secondary btn-edit-product"
                                            data-action="{{ route('products.edit', $item->id) }}"
                                            data-bs-target="#modal-form-update"
                                            data-bs-toggle="modal">
                                        <i class="dripicons-document-edit"></i>
                                    </button>
                                </div>
                                @endhasPermission
                                @hasPermission('product_delete')
                                <div class="col-sm-4">
                                    <button type="submit" class="btn btn-danger btn-delete-product"
                                            id="btn_delete"
                                            data-id="{{ $item->id }}"
                                            data-name-show="{{ $item->name }}"
                                            data-action="{{ route('products.destroy',$item->id) }}">
                                        <i class="dripicons-trash"></i>
                                    </button>
                                </div>
                                @endhasPermission
                            </div>
                        </div>
                    </td>
                </tr>
            @endforeach
            </tbody>
        @else
            <tbody>
                <tr>
                    <td colspan="5" class="text-center"><span style="font-size: 25px; color: #d8d8d8">No data...</span></td>
                </tr>
            </tbody>
        @endif
    </table>
    {{ $products->appends(request()->all())->links() }}
</div>

resources/views/admin/products/show.blade.php
<div class="row">
    <div class="col-md-12" style="margin: auto">
        <div class="card">
            <div class="card-body">
                <div class="detail-product">
                    <dl class="row">
                        <dt class="col-sm-4 text-end">Id :</dt>
                        <dd class="col-sm-8 text-center">{{ $product->id }}</dd>
                        <dt class="col-sm-4 text-end">Name :</dt>
                        <dd class="col-sm-8 text-center">{{ $product->name }}</dd>
                        <dt class="col-sm-4 text-end">Price :</dt>
                        <dd class="col-sm-8 text-center">{{ $product->price }}</dd>
                        <dt class="col-sm-4 text-end">Quantity :</dt>
                        <dd class="col-sm-8 text-center">{{ $product->quantity }}</dd>
                        <dt class="col-sm-4 text-end">Description :</dt>
                        <dd class="col-sm-8 text-center">{{ $product->description }}</dd>
                        <dt class="col-sm-4 text-end">Image :</dt>
                        <dd class="col-sm-8 text-center">
                            <img src="{{ $product->image }}" style="width: 40%" alt="">
                        </dd>
                        <dt class="col-sm-4 text-end">Category :</dt>
                        <dd class="col-sm-8 text-center">
                            @foreach($product->categories as $item)
                                <div class="col-sm text-center">
                                    <span class="badge bg-success">{{ $item->name }}</span>
                                </div>
                            @endforeach
                        </dd>
                    </dl>
                </div>
            </div>
        </div>
        <hr>
        <div class="mb-3 text-center">
            <button class="btn btn-rounded btn-primary" type="button" data-bs-dismiss="modal">Close</button>
        </div>
    </div>
</div>