routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', [HomeController::class, 'index'])->name('home')->middleware('auth');;

Route::name('users.')->prefix('users')->middleware('auth')->group(function (){
    Route::get('/',[UserController::class, 'index'])->name('index')->middleware('permission:user_list');
    Route::post('/',[UserController::class, 'store'])->name('store')->middleware('permission:user_create');
    Route::get('/create',[UserController::class, 'create'])->name('create')->middleware('permission:user_create');
    Route::get('/show/{id}',[UserController::class, 'show'])->name('show')->middleware('permission:user_show');
    Route::get('/edit/{id}',[UserController::class, 'edit'])->name('edit')->middleware('permission:user_edit');
    Route::put('/update/{id}',[UserController::class, 'update'])->name('update')->middleware('permission:user_edit');
    Route::delete('/destroy/{id}',[UserController::class, 'destroy'])->name('destroy')->middleware('permission:user_delete');
});


Route::prefix('roles')->name('roles.')->middleware('auth')->group(function (){
    Route::get('/',[RoleController::class, 'index'])->name('index')->middleware('permission:role_list');
    Route::post('/',[RoleController::class, 'store'])->name('store')->middleware('permission:role_create');
    Route::get('/create',[RoleController::class, 'create'])->name('create')->middleware('permission:role_create');
    Route::get('/show/{id}',[RoleController::class, 'show'])->name('show')->middleware('permission:role_show');
    Route::get('/edit/{id}',[RoleController::class, 'edit'])->name('edit')->middleware('permission:role_edit');
    Route::put('/update/{id}',[RoleController::class, 'update'])->name('update')->middleware('permission:role_edit');
    Route::delete('/destroy/{id}',[RoleController::class, 'destroy'])->name('destroy')->middleware('permission:role_delete');
});

Route::prefix('categories')->name('categories.')->middleware('auth')->group(function (){
    Route::get('/',[CategoryController::class, 'index'])->name('index')->middleware('permission:category_list');
    Route::post('/',[CategoryController::class, 'store'])->name('store')->middleware('permission:category_create');
    Route::get('/create',[CategoryController::class, 'create'])->name('create')->middleware('permission:category_create');
    Route::get('/show/{id}',[CategoryController::class, 'show'])->name('show')->middleware('permission:category_show');
    Route::get('/edit/{id}',[CategoryController::class, 'edit'])->name('edit')->middleware('permission:category_edit');
    Route::put('/update/{id}',[CategoryController::class, 'update'])->name('update')->middleware('permission:category_edit');
    Route::delete('/destroy/{id}',[CategoryController::class, 'destroy'])->name('destroy')->middleware('permission:category_delete');
});

Route::prefix('products')->name('products.')->middleware('auth')->group(function (){
    Route::get('/',[ProductController::class, 'index'])->name('index')->middleware('permission:product_list');
    Route::post('/',[ProductController::class, 'store'])->name('store')->middleware('permission:product_create');
    Route::get('list/',[ProductController::class,'list'])->name('list');
    Route::get('/show/{id}',[ProductController::class, 'show'])->name('show')->middleware('permission:product_show');
    Route::get('/create',[ProductController::class, 'create'])->name('create')->middleware('permission:product_create');
    Route::get('/edit/{id}',[ProductController::class, 'edit'])->name('edit')->middleware('permission:product_edit');
    Route::post('/update/{id}',[ProductController::class, 'update'])->name('update')->middleware('permission:product_edit');
    Route::delete('/destroy/{id}',[ProductController::class, 'destroy'])->name('destroy')->middleware('permission:product_delete');
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $table = 'categories';

    protected $fillable = [
        'name',
        'parent_id',
        'slug'
    ];

    public $timestamps = false;

    public function products()
    {
        return $this->hasMany(Product::class);
    }

    public function childrens()
    {
        return $this->hasMany(Category::class, 'parent_id', 'id');
    }

    public function parent()
    {
        return $this->belongsTo(Category::class, 'parent_id', 'id');
    }

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Category\CreateCategoryRequest;
use App\Http\Requests\Category\UpdateCategoryRequest;
use App\Models\Category;
use App\Services\CategoryService;

class CategoryController extends Controller
{

    protected CategoryService $categoryService;

    public function __construct(CategoryService $categoryService)
    {
        $this->categoryService = $categoryService;
    }

    public function index()
    {
        $listCategories = $this->categoryService->all();
        return view("admin.categories.index", compact('listCategories'));
    }

    public function show($id)
    {
        $category = $this->categoryService->findOrFail($id);
        return view("admin.categories.show", compact('category'));
    }

    public function create()
    {
        return view("admin.categories.create");
    }

    public function store(CreateCategoryRequest $request)
    {
        $this->categoryService->store($request);
        return redirect()->route('categories.index')->with('message', "Create category success.");
    }


    public function edit($id)
    {
        $category = $this->categoryService->findOrFail($id);
        return view("admin.categories.edit", compact('category'));
    }

    public function update(UpdateCategoryRequest $request, $id)
    {
        $this->categoryService->update($request, $id);
        return redirect()->route("categories.index")->with("message", "Update category success!");
    }

    public function destroy($id)
    {
        $this->categoryService->destroy($id);
        return redirect()->route("categories.index")->with("message", "Delete category success.");
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.layouts')
@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <h4 class="page-title">Create Category</h4>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('categories.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="modal-body">
                            @include('admin.layouts.form-errors')
                            <div class="mb-3">
                                <label>Name</label>
                                <input type="text" name="name" value="{{ old("name") }}" class="form-control" placeholder="Name">
                            </div>
                            <div class="mb-3">
                                <label>Category Parent</label>
                                <select name="parent_id" class="form-control col-sm-4" style="width: 200px">
                                    <option value="0">Category</option>
                                    @foreach($categories as $item)
                                        @if($item->parent_id == 0)
                                            <option value="{{ $item->id }}" {{ old("parent_id") == $item->id ? "selected" : '' }}>{{ $item->name }}</option>
                                        @endif
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <a type="button" href="{{ url()->previous() }}" class="btn btn-secondary btn-button">Back</a>
                            <button type="submit" class="btn btn-primary btn-button">Create</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.layouts')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="page-title-box">
                    <h4 class="page-title">Update Category</h4>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <form action="{{ route('categories.update',$category->id) }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @method('put')
                            <div class="modal-body">
                                @include('admin.layouts.form-errors')
                                <div class="mb-3">
                                    <label>Name</label>
                                    <input type="text" name="name" class="form-control" value="{{ $category->name }}" placeholder="Name">
                                </div>
                                <div class="mb-3">
                                    <label>Category Parent</label>
                                    <select name="parent_id" class="form-control col-sm-4" style="width: 200px">
                                        <option value="0" >Category</option>
                                        @foreach($categories as $item)
                                            @if($item->parent_id == 0)
                                                <option value="{{ $item->id }}" {{ $category->name ===  $item->name ? 'disabled' : ''}} {{ $category->parent_id == $item->id ? 'selected' : '' }}>{{ $item->name }}</option>
                                            @endif
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <a type="button" href="{{ url()->previous() }}" class="btn btn-secondary btn-button">Back</a>
                                <button type="submit" class="btn btn-primary btn-button">Update</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/categories/index.blade.php
@extends("admin.layouts.layouts")
@section("content")
    <div class="container-fluid">
        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box">
                    <h4 class="page-title">Category</h4>
                </div>
            </div>
        </div>
        <!-- end page title -->

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row mb-2">
                            <div class="col-sm-4">
                                @hasPermission('category_create')
                                <a href="{{ route("categories.create") }}">
                                    <button type="button" class="btn btn-danger mb-2">
                                        <i class="mdi mdi-plus-circle me-2"></i>Add Category
                                    </button>
                                </a>
                                @endhasPermission
                            </div>
                        </div>
                        <div class="table-responsive">
                            <table class="table table-centered table-bordered w-100 dt-responsive nowrap">
                                <thead class="table-light">
                                <tr>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th style="width: 85px;text-align: center">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @if(count($listCategories) != 0)
                                @foreach($listCategories as $item)
                                    <tr>
                                        <td>{{ $item->id }}</td>
                                        <td>{{ $item->name }}</td>
                                        <td>
                                            <div class="container">
                                                <div class="flex-class justify-content-center">
                                                    <div class="col-sm-4">
                                                        <a href="{{ route('categories.show', $item->id) }}"> <button type="button" class="btn btn-primary"><i class="dripicons-information"></i></button></a>
                                                    </div>
                                                    @hasPermission('category_edit')
                                                    <div class="col-sm-4">
                                                        <a href="{{ route('categories.edit', $item->id) }}"> <button type="button" class="btn btn-secondary"><i class="dripicons-document-edit"></i></button></a>
                                                    </div>
                                                    @endhasPermission
                                                    @hasPermission('category_delete')
                                                        <div class="col-sm-4">
                                                            <form id="delete-{{ $item->slug }}-{{$item->id}}" action="{{ route('categories.destroy',$item->id) }}" method="POST">
                                                                @csrf
                                                                @method('DELETE')
                                                            </form>
                                                            <button data-id="{{$item->id}}"
                                                                    data-name="{{ $item->slug }}"
                                                                    data-name-show="{{ $item->name }}"
                                                                    type="submit" class="btn btn-danger btn-delete">
                                                                <i class="dripicons-trash"></i>
                                                            </button>
                                                        </div>
                                                    @endhasPermission
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                                @else
                                    <tbody>
                                    <tr>
                                        <td colspan="5" class="text-center"><span style="font-size: 25px; color: #d8d8d8">No data...</span></td>
                                    </tr>
                                    </tbody>
                                @endif
                            </table>
                            {{ $listCategories->appends(request()->all())->links() }}
                        </div>
                    </div> <!-- end card-body-->
                </div> <!-- end card-->
            </div> <!-- end col -->
        </div>
    </div>
    @push('scripts')
        <script src="{{asset('js/category.js')}}"></script>
    @endpush
@endsection

resources/views/admin/categories/show.blade.php
@extends("admin.layouts.layouts")
@section("content")
    <div class="container-fluid">
        <!-- start page title -->
        <div class="row">
            <div class="col-md-4" style="margin: auto;padding: 10px;text-align: center">
                <h2 class="page-title">Detail cate {{ $category->name }}</h2>

            </div>
        </div>
        <!-- end page title -->
        <div class="row">
            <div class="col-md-6" style="margin: auto">
                <div class="card">
                    <div class="card-body">
                        <dl class="row">
                            <dt class="col-sm-4">Id :</dt>
                            <dd class="col-sm-8">{{ $category->id }}</dd>
                            <dt class="col-sm-4">Name :</dt>
                            <dd class="col-sm-8">{{ $category->name }}</dd>
                            <dt class="col-sm-4">Slug :</dt>
                            <dd class="col-sm-8">{{ $category->slug }}</dd>
                            @if($category->parent != null)
                                <dt class="col-sm-4">Category parent :</dt>
                                <dd class="col-sm-8">
                                    <div class="row">
                                        <div class="col-sm-4">
                                            <span class="badge bg-success">{{ $category->parent->name }}</span>
                                        </div>
                                    </div>
                                </dd>
                            @endif
                        </dl>
                    </div>
                    <a type="button" href="{{ url()->previous() }}" class="btn btn-primary btn-button">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection